{{- if .Values.app.envVarsCM }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common-app.labels" . | nindent 4 }}
data: 
{{- range .Values.app.envVarsCM }}
  {{ .name }}: {{ .value | quote }}
{{- end }}
{{- end }}
