{{- if .Values.app.envVarsSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common-app.labels" . | nindent 4 }}
type: Opaque
data: 
{{- range .Values.app.envVarsSecret }}
  {{ .name }}: {{ .value | b64enc | quote}}
{{- end }}
{{- end }}
