apiVersion: v1
kind: Service
metadata:
  name: {{ include "common-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.containerPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "common-app.selectorLabels" . | nindent 4 }}
