{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common-app.labels" . | nindent 4 }}
  annotations:
{{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
{{- if .Values.prometheus.metrics }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.app.port }}"
    prometheus.io/path: "{{ .Values.prometheus.path }}"
{{- end }}

spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $value := .Values.service.ports }}
    - name: {{ $key }}
{{ toYaml $value | indent 6 }}
    {{- end }}
  selector:
    {{- include "common-app.selectorLabels" . | nindent 4 }}
{{- end }}